[package]
name = "bitbadges-cosmwasm"
version = "0.0.8"
authors = ["Lyubomir Yonchev <lyubomir.yonchev@limechain.tech>", "Trevor Miller <trevormil@comcast.net>"]
edition = "2018"
description = "Bindings for CosmWasm contracts to call into custom modules of BitBadges Node"
repository = "https://github.com/bitbadges/bitbadges-cosmwasm-bindings"
license = "Apache-2.0"
readme = "README.md"

[features]
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = "1.0.0-beta"
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }

[dev-dependencies]
cosmwasm-schema = "1.0.0-beta"
